/* Generated by scripts/capture-projects.mjs. Do not edit by hand. */
export type Shot = { src: string; srcSet: string; width: number; height: number };

export const SHOTS = {
  "mb-hair-salon": {
    src: "/projects/mb-hair-salon-960.webp",
    srcSet: "/projects/mb-hair-salon-640.webp 640w, /projects/mb-hair-salon-960.webp 960w, /projects/mb-hair-salon-1280.webp 1280w, /projects/mb-hair-salon-1600.webp 1600w",
    width: 1440,
    height: 900,
  },
  "mb-hair-salon-mobile": {
    src: "/projects/mb-hair-salon-mobile-600.webp",
    srcSet: "/projects/mb-hair-salon-mobile-300.webp 300w, /projects/mb-hair-salon-mobile-450.webp 450w, /projects/mb-hair-salon-mobile-600.webp 600w, /projects/mb-hair-salon-mobile-810.webp 810w",
    width: 390,
    height: 844,
  },
  "mb-hair-salon-mobile-gallery": {
    src: "/projects/mb-hair-salon-mobile-gallery-600.webp",
    srcSet: "/projects/mb-hair-salon-mobile-gallery-300.webp 300w, /projects/mb-hair-salon-mobile-gallery-450.webp 450w, /projects/mb-hair-salon-mobile-gallery-600.webp 600w, /projects/mb-hair-salon-mobile-gallery-810.webp 810w",
    width: 390,
    height: 844,
  },
  "keeper": {
    src: "/projects/keeper-960.webp",
    srcSet: "/projects/keeper-640.webp 640w, /projects/keeper-960.webp 960w, /projects/keeper-1280.webp 1280w, /projects/keeper-1600.webp 1600w",
    width: 1440,
    height: 900,
  },
  "automation-desk": {
    src: "/projects/automation-desk-960.webp",
    srcSet: "/projects/automation-desk-640.webp 640w, /projects/automation-desk-960.webp 960w, /projects/automation-desk-1280.webp 1280w, /projects/automation-desk-1600.webp 1600w",
    width: 1440,
    height: 900,
  },
  "invoice": {
    src: "/projects/invoice-960.webp",
    srcSet: "/projects/invoice-640.webp 640w, /projects/invoice-960.webp 960w, /projects/invoice-1213.webp 1213w",
    width: 1213,
    height: 758,
  },
  "invoice-nav": {
    src: "/projects/invoice-nav-960.webp",
    srcSet: "/projects/invoice-nav-640.webp 640w, /projects/invoice-nav-960.webp 960w, /projects/invoice-nav-1280.webp 1280w, /projects/invoice-nav-1600.webp 1600w",
    width: 2000,
    height: 1250,
  },
} satisfies Record<string, Shot>;
